apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
resources:
  - deployment.yaml
  - service.yaml
  - service.lb.yaml
  - nginx-config.yaml

images:
  - name: nginx
    newName: nginx
    newTag: latest
