apiVersion: v1
kind: Service
metadata:
  name: nginx-service-neg
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{"name": "proxy-nginx-neg"}}}'
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
